# Generated by Django 3.2.16 on 2024-01-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240125_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='pub_date',
        ),
    ]
